#!/bin/bash
# Stop hook: フィードバック収集スクリプト
# セッション終了時に条件判断してフィードバックを保存

set -euo pipefail

FEEDBACK_DIR="$HOME/.claude/feedback"
mkdir -p "$FEEDBACK_DIR"

# 標準入力からhookデータを読み取り
INPUT=$(cat)

# セッション情報を環境変数から取得
SESSION_ID="${CLAUDE_SESSION_ID:-unknown}"
STOP_REASON="${CLAUDE_STOP_REASON:-unknown}"

# hookデータからトランスクリプト情報を抽出
# jqがあれば使用、なければ簡易パース
if command -v jq &> /dev/null; then
    MESSAGE_COUNT=$(echo "$INPUT" | jq -r '.transcript | length // 0' 2>/dev/null || echo "0")
    TOOL_USES=$(echo "$INPUT" | jq -r '[.transcript[].content[]? | select(.type == "tool_use")] | length // 0' 2>/dev/null || echo "0")
    # Write/Edit/Bash ツールの使用をチェック
    CODE_CHANGES=$(echo "$INPUT" | jq -r '[.transcript[].content[]? | select(.type == "tool_use") | select(.name | test("Write|Edit|Bash"))] | length // 0' 2>/dev/null || echo "0")
else
    # jqがない場合は簡易カウント
    MESSAGE_COUNT=$(echo "$INPUT" | grep -c '"role"' 2>/dev/null || echo "0")
    TOOL_USES=$(echo "$INPUT" | grep -c '"tool_use"' 2>/dev/null || echo "0")
    CODE_CHANGES=$(echo "$INPUT" | grep -cE '"name":\s*"(Write|Edit|Bash)"' 2>/dev/null || echo "0")
fi

# 収集条件の判定
SHOULD_COLLECT=false

# 条件1: コード変更があった（Write/Edit/Bash使用）
if [ "$CODE_CHANGES" -gt 0 ]; then
    SHOULD_COLLECT=true
    REASON="code_changes"
fi

# 条件2: 3ステップ以上のツール使用
if [ "$TOOL_USES" -ge 3 ]; then
    SHOULD_COLLECT=true
    REASON="complex_task"
fi

# 条件3: 多くのメッセージ交換（実質的なセッション）
if [ "$MESSAGE_COUNT" -ge 6 ]; then
    SHOULD_COLLECT=true
    REASON="substantial_session"
fi

# スキップ条件: メッセージが少なすぎる
if [ "$MESSAGE_COUNT" -lt 4 ]; then
    SHOULD_COLLECT=false
fi

# 収集しない場合は終了
if [ "$SHOULD_COLLECT" = false ]; then
    echo '{"continue": true}'
    exit 0
fi

# フィードバックファイル生成
DATE=$(date +%Y%m%d)
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# シーケンス番号を決定
SEQ=1
while [ -f "$FEEDBACK_DIR/fb-$DATE-$(printf '%03d' $SEQ).yaml" ]; do
    SEQ=$((SEQ + 1))
done
FILENAME="fb-$DATE-$(printf '%03d' $SEQ).yaml"

# フィードバックテンプレート生成
cat > "$FEEDBACK_DIR/$FILENAME" << EOF
# Auto-generated by Stop hook
id: fb-$DATE-$(printf '%03d' $SEQ)
created_at: $TIMESTAMP
session_id: $SESSION_ID
stop_reason: $STOP_REASON

# セッション統計
stats:
  message_count: $MESSAGE_COUNT
  tool_uses: $TOOL_USES
  code_changes: $CODE_CHANGES
  collection_reason: $REASON

# 以下は手動または /improve で更新
task_summary: "TODO: タスク要約を記入"
outcome:
  success: null
  score: null
  rationale: "TODO: 評価理由を記入"
issues: []

# プライバシー
privacy:
  redacted: false
EOF

# 成功メッセージを出力（Claude Code に表示される）
echo '{"continue": true, "stopReason": "フィードバックを保存しました: '"$FILENAME"'"}'
